title: deckerdev.com
description: ''
baseurl: ''
url: 'http://deckerdev.com'
timezone: America/Phoenix
twitter_username: decker_dev
github_username: robdecker
google_analytics: UA-738267-3
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
github:
  - metadata
