---
title: deckerdev.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: ''
baseurl: ''
url: http://deckerdev.com
twitter_username: decker_dev
github_username: robdecker
google_analytics: UA-738267-3
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: jekyll-theme-hacker
plugins:
- jekyll-feed
github:
- metadata
